language: java
jdk: oraclejdk8
env:
  - ACTIVATOR_VERSION=1.3.12
before_install:
  - git clone https://github.com/hbz/metafacture-core.git
  - cd metafacture-core
  - mvn clean install -DskipTests=true
  - cd ..
  - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
script:
  - activator-${ACTIVATOR_VERSION}-minimal/bin/activator update test
