#defaultView:ImageGrid
SELECT ?image ?itemLabel ?isil
WHERE
{
  ?item wdt:P18 ?image .  
  ?item wdt:P791 ?isil  .
  FILTER (regex(?isil, "(DE)-.*")).
  SERVICE wikibase:label { bd:serviceParam wikibase:language "de" }
}