name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Install metafacture-core
      run: |
        git clone https://github.com/metafacture/metafacture-core.git
        cd metafacture-core
        ./gradlew publishToMavenLocal
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt -Djava.security.manager=allow  update test
